  
pool:
    vmImage: 'ubuntu-latest'


parameters:
- name: "branch"
  displayName: Git branch/tag/commit id
  type: string
  default: 'main'

steps:
- task: Maven@3
  inputs:
    mavenPomFile: 'gs-spring-boot-master/app/pom.xml'
    publishJUnitResults: true
    testResultsFiles: '**/surefire-reports/TEST-*.xml'
    javaHomeOption: 'JDKVersion'
    mavenVersionOption: 'Default'
    mavenAuthenticateFeed: false
    effectivePomSkip: false
    sonarQubeRunAnalysis: false

- task: CopyFiles@2
  inputs:
    SourceFolder: '$(System.DefaultWorkingDirectory)'
    Contents: '**/*.jar'
    TargetFolder: '$(Build.ArtifactStagingDirectory)'

- task: UniversalPackages@0
  displayName: Universal Publish
  inputs:
    command: publish
    publishDirectory: '$(Build.ArtifactStagingDirectory)'
    vstsFeedPublish: 'springboot/artifacts'
    vstsFeedPackagePublish: 'springboot'
    packagePublishDescription: 'springboot package'