#azure-pipelines.yml

# trigger for this pipeline
trigger:
  - master

# pool used in pipeline
pool:
  vmImage: 'ubuntu-latest'



stages:
- stage: CI
  displayName: 'Continuous Integration'
  jobs:
  - job: Build
  - job: Publish


- stage: 'Dev'
  displayName: 'Release to Dev'
  dependsOn: CI
  jobs:
  - job: 
    steps:
  - script: echo stage dev!

- stage: 'Test'
  displayName: 'Release to Test'
  dependsOn: Dev
  jobs:
  - job: 
    steps:
  - script: echo stage test!

- stage: 'ReleaseA'
  displayName: 'Release to production for Company A'
  dependsOn: Test
  jobs:
    steps:
  - script: echo stage ReleaseA!

- stage: 'ReleaseB'
  displayName: 'Release to production for Company B'
  dependsOn: Test
  jobs:
    steps:
  - script: echo stage ReleaseB!