#azure-pipelines.yml

# trigger for this pipeline
trigger:
  - master

# pool used in pipeline
pool:
  vmImage: 'ubuntu-latest'



stages:
- stage: CI
  displayName: 'Continuous Integration'
  jobs:
  - job: Build
  - job: Publish


- stage: 'Dev'
  displayName: 'Release to Dev'
  dependsOn: CI


- stage: 'Test'
  displayName: 'Release to Test'
  dependsOn: Dev
 

- stage: 'ReleaseA'
  displayName: 'Release to production for Company A'
  dependsOn: Test


- stage: 'ReleaseB'
  displayName: 'Release to production for Company B'
  dependsOn: Test